import React, { useRef } from 'react';
import { X, Download, Share2, Mail, FileText } from 'lucide-react';

export type DietPlanData = {
  memberName: string;
  age: number;
  gender: string;
  height: string;
  weight: string;
  goal: string;
  activityLevel: string;
  dietaryPreference: string;
  budgetPreference: string;
  mealPreferences?: string;
  mealsPerDay: number;
  allergies: string;
  medicalConditions?: string;
  targetWeight?: string;
  dailyCalories: number;
  macros: {
    protein: string;
    carbs: string;
    fats: string;
  };
  schedule: {
    meal: string;
    items: string;
    portion: string;
  }[];
  guidelines: {
    water: string;
    supplements: string;
    avoid: string;
    advice: string;
  };
};

export default function DietPlanModal({
  isOpen,
  onClose,
  dietPlan,
  gymName,
  gstNumber,
  memberEmail,
  memberPhone
}: {
  isOpen: boolean;
  onClose: () => void;
  dietPlan: DietPlanData | null;
  gymName: string;
  gstNumber?: string;
  memberEmail?: string;
  memberPhone?: string;
}) {
  const printRef = useRef<HTMLDivElement>(null);

  if (!isOpen || !dietPlan) return null;

  const handleDownloadPDF = () => {
    window.print();
  };

  const handleWhatsApp = () => {
    const text = `Hi ${dietPlan.memberName},\n\nHere is your personalized diet plan generated by ${gymName}${gstNumber ? `\nGST: ${gstNumber}` : ''}.\n\nGoal: ${dietPlan.goal}\nDaily Calories: ${dietPlan.dailyCalories} kcal\n\nPlease collect your detailed PDF plan from the gym.\n\nStay fit!`;
    const url = `https://wa.me/${memberPhone ? memberPhone.replace(/\D/g, '') : ''}?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const handleEmail = () => {
    const subject = `${gymName} - Your Personalized Diet Plan`;
    const body = `Hi ${dietPlan.memberName},\n\nYour personalized diet plan has been generated by ${gymName}.\n\nGoal: ${dietPlan.goal}\nDaily Calories: ${dietPlan.dailyCalories} kcal\n\nPlease find the attached PDF or collect it from the gym.${gstNumber ? `\n\nGST: ${gstNumber}` : ''}\n\nBest regards,\n${gymName}`;
    const url = `mailto:${memberEmail || ''}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(url, '_blank');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-neutral-900/50 backdrop-blur-sm print:static print:bg-white print:p-0 print:block">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden print:shadow-none print:max-w-none print:max-h-none print:overflow-visible print:rounded-none">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-neutral-100 bg-white print:hidden">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-100 flex items-center justify-center text-emerald-600">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-neutral-900">Diet Plan</h2>
              <p className="text-xs text-neutral-500">For {dietPlan.memberName}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={handleDownloadPDF} className="p-2 text-neutral-600 hover:bg-neutral-100 rounded-lg transition-colors" title="Download PDF">
              <Download className="w-5 h-5" />
            </button>
            <button onClick={handleWhatsApp} className="p-2 text-emerald-600 hover:bg-emerald-50 rounded-lg transition-colors" title="Send via WhatsApp">
              <Share2 className="w-5 h-5" />
            </button>
            <button onClick={handleEmail} className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors" title="Send via Email">
              <Mail className="w-5 h-5" />
            </button>
            <div className="w-px h-6 bg-neutral-200 mx-1"></div>
            <button onClick={onClose} className="p-2 text-neutral-400 hover:text-neutral-600 hover:bg-neutral-100 rounded-lg transition-colors">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Scrollable Content */}
        <div className="flex-1 overflow-y-auto p-6 bg-neutral-50 print:overflow-visible print:bg-white print:p-0">
          {/* PDF Container */}
          <div className="flex justify-center print:block">
            <div 
              ref={printRef}
              className="bg-white p-10 shadow-sm border border-neutral-200 w-full max-w-[794px] min-h-[1123px] print:shadow-none print:border-none print:p-0 print:w-full print:max-w-none print:min-h-0" // A4 proportions
              style={{ fontFamily: 'sans-serif' }}
            >
              {/* PDF Header */}
              <div className="text-center mb-8 border-b-2 border-neutral-900 pb-6">
                <h1 className="text-3xl font-black text-neutral-900 uppercase tracking-tight mb-2">{gymName}</h1>
                {gstNumber && <p className="mb-2 text-xs font-bold uppercase tracking-[0.2em] text-neutral-500">GST: {gstNumber}</p>}
                <h2 className="text-xl font-medium text-neutral-600 uppercase tracking-widest">Personalized Diet Plan</h2>
              </div>

              {/* Member Profile */}
              <div className="mb-8">
                <h3 className="text-sm font-bold text-neutral-900 uppercase tracking-wider mb-4 border-b border-neutral-200 pb-2">Member Profile</h3>
                <div className="grid grid-cols-2 gap-y-3 gap-x-8 text-sm">
                  <div className="flex justify-between"><span className="text-neutral-500">Name:</span> <span className="font-semibold text-neutral-900">{dietPlan.memberName}</span></div>
                  <div className="flex justify-between"><span className="text-neutral-500">Goal:</span> <span className="font-semibold text-neutral-900">{dietPlan.goal}</span></div>
                  <div className="flex justify-between"><span className="text-neutral-500">Age/Gender:</span> <span className="font-semibold text-neutral-900">{dietPlan.age} / {dietPlan.gender}</span></div>
                  <div className="flex justify-between"><span className="text-neutral-500">Activity Level:</span> <span className="font-semibold text-neutral-900">{dietPlan.activityLevel}</span></div>
                  <div className="flex justify-between"><span className="text-neutral-500">Height/Weight:</span> <span className="font-semibold text-neutral-900">{dietPlan.height} / {dietPlan.weight}</span></div>
                  <div className="flex justify-between"><span className="text-neutral-500">Preference:</span> <span className="font-semibold text-neutral-900">{dietPlan.dietaryPreference}</span></div>
                  <div className="flex justify-between"><span className="text-neutral-500">Budget:</span> <span className="font-semibold text-neutral-900">{dietPlan.budgetPreference}</span></div>
                  {dietPlan.mealPreferences && <div className="flex justify-between"><span className="text-neutral-500">Likes/Dislikes:</span> <span className="font-semibold text-neutral-900">{dietPlan.mealPreferences}</span></div>}
                  {dietPlan.targetWeight && <div className="flex justify-between"><span className="text-neutral-500">Target Weight:</span> <span className="font-semibold text-neutral-900">{dietPlan.targetWeight}</span></div>}
                  {dietPlan.allergies && <div className="flex justify-between"><span className="text-neutral-500">Allergies:</span> <span className="font-semibold text-red-600">{dietPlan.allergies}</span></div>}
                </div>
              </div>

              {/* Targets */}
              <div className="mb-8 bg-neutral-50 p-4 rounded-xl border border-neutral-100">
                <div className="text-center mb-4">
                  <span className="text-xs font-bold text-neutral-500 uppercase tracking-wider">Daily Target</span>
                  <div className="text-3xl font-black text-neutral-900">{dietPlan.dailyCalories} <span className="text-lg font-medium text-neutral-500">kcal</span></div>
                </div>
                <div className="grid grid-cols-3 gap-4 text-center divide-x divide-neutral-200">
                  <div>
                    <div className="text-xs font-bold text-neutral-500 uppercase">Protein</div>
                    <div className="text-lg font-bold text-neutral-900">{dietPlan.macros.protein}</div>
                  </div>
                  <div>
                    <div className="text-xs font-bold text-neutral-500 uppercase">Carbs</div>
                    <div className="text-lg font-bold text-neutral-900">{dietPlan.macros.carbs}</div>
                  </div>
                  <div>
                    <div className="text-xs font-bold text-neutral-500 uppercase">Fats</div>
                    <div className="text-lg font-bold text-neutral-900">{dietPlan.macros.fats}</div>
                  </div>
                </div>
              </div>

              {/* Schedule */}
              <div className="mb-8">
                <h3 className="text-sm font-bold text-neutral-900 uppercase tracking-wider mb-4 border-b border-neutral-200 pb-2">Meal Schedule</h3>
                <div className="space-y-4">
                  {dietPlan.schedule.map((meal, idx) => (
                    <div key={idx} className="flex gap-4 p-3 rounded-lg hover:bg-neutral-50 transition-colors border border-transparent hover:border-neutral-100">
                      <div className="w-24 shrink-0">
                        <span className="text-xs font-bold text-emerald-600 uppercase tracking-wider">{meal.meal}</span>
                      </div>
                      <div className="flex-1">
                        <p className="text-sm font-medium text-neutral-900">{meal.items}</p>
                        <p className="text-xs text-neutral-500 mt-1">Portion: {meal.portion}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Guidelines */}
              <div className="mb-8">
                <h3 className="text-sm font-bold text-neutral-900 uppercase tracking-wider mb-4 border-b border-neutral-200 pb-2">Health Guidelines</h3>
                <div className="grid grid-cols-2 gap-6 text-sm">
                  <div>
                    <span className="block text-xs font-bold text-neutral-500 uppercase mb-1">Hydration</span>
                    <p className="text-neutral-900">{dietPlan.guidelines.water}</p>
                  </div>
                  <div>
                    <span className="block text-xs font-bold text-neutral-500 uppercase mb-1">Supplements</span>
                    <p className="text-neutral-900">{dietPlan.guidelines.supplements}</p>
                  </div>
                  <div>
                    <span className="block text-xs font-bold text-neutral-500 uppercase mb-1">Foods to Avoid</span>
                    <p className="text-red-600 font-medium">{dietPlan.guidelines.avoid}</p>
                  </div>
                  <div>
                    <span className="block text-xs font-bold text-neutral-500 uppercase mb-1">General Advice</span>
                    <p className="text-neutral-900">{dietPlan.guidelines.advice}</p>
                  </div>
                </div>
              </div>

              {/* Footer */}
              <div className="mt-16 pt-6 border-t border-neutral-200 text-center">
                <p className="text-xs text-neutral-400 italic">Prepared by GymAssist AI for {gymName}</p>
                {gstNumber && <p className="mt-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-neutral-300">GST: {gstNumber}</p>}
                <p className="text-[10px] text-neutral-300 mt-1">This is an AI-generated diet plan. Please consult a healthcare professional before starting any new diet.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
