import React, { useRef } from 'react';
import { X, Download, Share2, Mail, Dumbbell } from 'lucide-react';

export type WorkoutPlanData = {
  memberName: string;
  goal: string;
  experienceLevel: string;
  daysPerWeek: number;
  duration: string;
  targetMuscleGroups: string;
  injuries?: string;
  schedule: {
    day: string;
    focus: string;
    exercises: {
      name: string;
      sets: string;
      reps: string;
      rest: string;
    }[];
  }[];
  guidelines: {
    warmup: string;
    cooldown: string;
    recovery: string;
    progressiveOverload: string;
  };
};

export default function WorkoutPlanModal({
  isOpen,
  onClose,
  workoutPlan,
  gymName,
  gstNumber,
  memberEmail,
  memberPhone
}: {
  isOpen: boolean;
  onClose: () => void;
  workoutPlan: WorkoutPlanData | null;
  gymName: string;
  gstNumber?: string;
  memberEmail?: string;
  memberPhone?: string;
}) {
  const printRef = useRef<HTMLDivElement>(null);

  if (!isOpen || !workoutPlan) return null;

  const handleDownloadPDF = () => {
    window.print();
  };

  const handleWhatsApp = () => {
    const text = `Hi ${workoutPlan.memberName},\n\nHere is your personalized workout plan generated by ${gymName}${gstNumber ? `\nGST: ${gstNumber}` : ''}.\n\nGoal: ${workoutPlan.goal}\nExperience: ${workoutPlan.experienceLevel}\nDays per week: ${workoutPlan.daysPerWeek}\n\nPlease collect your detailed PDF plan from the gym.\n\nLet's crush those goals!`;
    const url = `https://wa.me/${memberPhone ? memberPhone.replace(/\D/g, '') : ''}?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const handleEmail = () => {
    const subject = `${gymName} - Your Personalized Workout Plan`;
    const body = `Hi ${workoutPlan.memberName},\n\nYour personalized workout plan has been generated by ${gymName}.\n\nGoal: ${workoutPlan.goal}\nExperience: ${workoutPlan.experienceLevel}\nDays per week: ${workoutPlan.daysPerWeek}\n\nPlease find the attached PDF or collect it from the gym.${gstNumber ? `\n\nGST: ${gstNumber}` : ''}\n\nBest regards,\n${gymName}`;
    const url = `mailto:${memberEmail || ''}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(url, '_blank');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-neutral-900/50 backdrop-blur-sm print:static print:bg-white print:p-0 print:block">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden print:shadow-none print:max-w-none print:max-h-none print:overflow-visible print:rounded-none">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-neutral-100 bg-white print:hidden">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-100 flex items-center justify-center text-blue-600">
              <Dumbbell className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-neutral-900">Workout Plan</h2>
              <p className="text-xs text-neutral-500">For {workoutPlan.memberName}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={handleDownloadPDF} className="p-2 text-neutral-600 hover:bg-neutral-100 rounded-lg transition-colors" title="Download PDF">
              <Download className="w-5 h-5" />
            </button>
            <button onClick={handleWhatsApp} className="p-2 text-emerald-600 hover:bg-emerald-50 rounded-lg transition-colors" title="Send via WhatsApp">
              <Share2 className="w-5 h-5" />
            </button>
            <button onClick={handleEmail} className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors" title="Send via Email">
              <Mail className="w-5 h-5" />
            </button>
            <div className="w-px h-6 bg-neutral-200 mx-1"></div>
            <button onClick={onClose} className="p-2 text-neutral-400 hover:text-neutral-600 hover:bg-neutral-100 rounded-lg transition-colors">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Scrollable Content */}
        <div className="flex-1 overflow-y-auto p-6 bg-neutral-50 print:overflow-visible print:bg-white print:p-0">
          {/* PDF Container */}
          <div className="flex justify-center print:block">
            <div 
              ref={printRef}
              className="bg-white p-10 shadow-sm border border-neutral-200 w-full max-w-[794px] min-h-[1123px] print:shadow-none print:border-none print:p-0 print:w-full print:max-w-none print:min-h-0" // A4 proportions
              style={{ fontFamily: 'sans-serif' }}
            >
              {/* PDF Header */}
              <div className="text-center mb-8 border-b-2 border-neutral-900 pb-6">
                <h1 className="text-3xl font-black text-neutral-900 uppercase tracking-tight mb-2">{gymName}</h1>
                {gstNumber && <p className="mb-2 text-xs font-bold uppercase tracking-[0.2em] text-neutral-500">GST: {gstNumber}</p>}
                <h2 className="text-xl font-medium text-neutral-600 uppercase tracking-widest">Personalized Workout Plan</h2>
              </div>

              {/* Member Profile */}
              <div className="mb-8">
                <h3 className="text-sm font-bold text-neutral-900 uppercase tracking-wider mb-4 border-b border-neutral-200 pb-2">Member Profile</h3>
                <div className="grid grid-cols-2 gap-y-3 gap-x-8 text-sm">
                  <div className="flex justify-between"><span className="text-neutral-500">Name:</span> <span className="font-semibold text-neutral-900">{workoutPlan.memberName}</span></div>
                  <div className="flex justify-between"><span className="text-neutral-500">Goal:</span> <span className="font-semibold text-neutral-900">{workoutPlan.goal}</span></div>
                  <div className="flex justify-between"><span className="text-neutral-500">Experience Level:</span> <span className="font-semibold text-neutral-900">{workoutPlan.experienceLevel}</span></div>
                  <div className="flex justify-between"><span className="text-neutral-500">Days/Week:</span> <span className="font-semibold text-neutral-900">{workoutPlan.daysPerWeek}</span></div>
                  <div className="flex justify-between"><span className="text-neutral-500">Duration:</span> <span className="font-semibold text-neutral-900">{workoutPlan.duration}</span></div>
                  <div className="flex justify-between"><span className="text-neutral-500">Focus:</span> <span className="font-semibold text-neutral-900">{workoutPlan.targetMuscleGroups}</span></div>
                  {workoutPlan.injuries && <div className="flex justify-between col-span-2"><span className="text-neutral-500">Injuries/Limitations:</span> <span className="font-semibold text-red-600">{workoutPlan.injuries}</span></div>}
                </div>
              </div>

              {/* Weekly Schedule */}
              <div className="mb-8">
                <h3 className="text-sm font-bold text-neutral-900 uppercase tracking-wider mb-4 border-b border-neutral-200 pb-2">Weekly Schedule</h3>
                <div className="space-y-6">
                  {workoutPlan.schedule.map((day, idx) => (
                    <div key={idx} className="bg-neutral-50 rounded-xl border border-neutral-200 overflow-hidden" style={{ pageBreakInside: 'avoid' }}>
                      <div className="bg-neutral-100 px-4 py-3 border-b border-neutral-200 flex justify-between items-center">
                        <span className="font-bold text-neutral-900">{day.day}</span>
                        <span className="text-sm font-medium text-blue-600 bg-blue-50 px-3 py-1 rounded-full">{day.focus}</span>
                      </div>
                      {day.exercises.length > 0 ? (
                        <table className="w-full text-sm text-left">
                          <thead className="bg-white border-b border-neutral-200 text-xs uppercase text-neutral-500">
                            <tr>
                              <th className="px-4 py-3 font-semibold">Exercise</th>
                              <th className="px-4 py-3 font-semibold w-20 text-center">Sets</th>
                              <th className="px-4 py-3 font-semibold w-24 text-center">Reps</th>
                              <th className="px-4 py-3 font-semibold w-24 text-center">Rest</th>
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-neutral-100 bg-white">
                            {day.exercises.map((ex, i) => (
                              <tr key={i}>
                                <td className="px-4 py-3 font-medium text-neutral-900">{ex.name}</td>
                                <td className="px-4 py-3 text-center text-neutral-600">{ex.sets}</td>
                                <td className="px-4 py-3 text-center text-neutral-600">{ex.reps}</td>
                                <td className="px-4 py-3 text-center text-neutral-600">{ex.rest}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      ) : (
                        <div className="p-4 text-center text-sm text-neutral-500 bg-white">Rest Day</div>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Guidelines */}
              <div className="mb-8" style={{ pageBreakInside: 'avoid' }}>
                <h3 className="text-sm font-bold text-neutral-900 uppercase tracking-wider mb-4 border-b border-neutral-200 pb-2">Guidelines & Advice</h3>
                <div className="grid grid-cols-2 gap-6">
                  <div className="bg-neutral-50 p-4 rounded-xl border border-neutral-100">
                    <h4 className="text-xs font-bold text-neutral-500 uppercase mb-2">Warm-up</h4>
                    <p className="text-sm text-neutral-700 leading-relaxed">{workoutPlan.guidelines.warmup}</p>
                  </div>
                  <div className="bg-neutral-50 p-4 rounded-xl border border-neutral-100">
                    <h4 className="text-xs font-bold text-neutral-500 uppercase mb-2">Cool-down & Recovery</h4>
                    <p className="text-sm text-neutral-700 leading-relaxed">{workoutPlan.guidelines.cooldown} {workoutPlan.guidelines.recovery}</p>
                  </div>
                  <div className="bg-neutral-50 p-4 rounded-xl border border-neutral-100 col-span-2">
                    <h4 className="text-xs font-bold text-neutral-500 uppercase mb-2">Progressive Overload</h4>
                    <p className="text-sm text-neutral-700 leading-relaxed">{workoutPlan.guidelines.progressiveOverload}</p>
                  </div>
                </div>
              </div>

              {/* Footer */}
              <div className="mt-12 pt-6 border-t border-neutral-200 text-center">
                <p className="text-xs text-neutral-400 uppercase tracking-widest">Prepared by GymAssist AI for {gymName}</p>
                {gstNumber && <p className="mt-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-neutral-300">GST: {gstNumber}</p>}
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
